[package]
name = "booruDownloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.77"
pgbar = "0.3.1"
reqwest = { version = "0.11.23", features = ["blocking"] }
tokio = { version = "1.35.1", features = ["full"] }
